### ISSUE TITLE
Does the ClickHouse dictionary support .mmdb files?

### ISSUE THREAD

**Issue by 7hong** [AlexeyKupershtokh/clickhouse-maxmind-geoip#10]
Does the ClickHouse dictionary support.mmdb files? Rather than CSV。

**Comment by Slach** [comment]
No,  but you can try to make create UDF which will use maxmind library in your favorite language
https://clickhouse.com/docs/en/sql-reference/functions/#executable-user-defined-functions

**Comment by 7hong** [comment]
Thanks for your reply.
 I am planning to do this, but I doubt if the performance is poor

**Comment by Slach** [comment]
try golang + https://github.com/oschwald/maxminddb-golang

**Comment by 7hong** [comment]
I am looking for how to convert MMDB files to CSV. But the Java API can only provide key-value queries.
The GO reader you provide seems to be able to foreach mmdbfile.

networks := db.Networks(maxminddb.SkipAliasedNetworks)
