### ISSUE TITLE
Provide SQL for creating tables

### ISSUE THREAD

**Issue by AlexeyKupershtokh** [AlexeyKupershtokh/clickhouse-maxmind-geoip#2]
There's a possibility to query dictionaries like regular tables and join them: https://clickhouse.yandex/docs/en/operations/table_engines/dictionary/

Queries to join dictionaries to be provided

**Comment by pachico** [comment]
@AlexeyKupershtokh I didn't find out how to query those tables. Any tips?

**Comment by Slach** [comment]
@pachico SELECT works as select from any other table type, look to https://clickhouse.com/docs/en/engines/table-engines/special/dictionary/
