### ISSUE TITLE
MaxMind CSV field 'prefix' has changed to 'network'

### ISSUE THREAD

**Issue by jagu2012** [AlexeyKupershtokh/clickhouse-maxmind-geoip#7]
As of March 2022 these files (and maybe more) have a slightly different csv header to the ones they had when this project was created.

eg (note the very first field)
GeoLite2-City-Blocks-IPv4.csv
network,geoname_id,registered_country_geoname_id,represented_country_geoname_id,is_anonymous_proxy,is_satellite_provider,postal_code,latitude,longitude,accuracy_radius
1.0.0.0/24,2077456,2077456,,0,0,,-33.4940,143.2104,1000
1.0.1.0/24,1814991,1814991,,0,0,,34.7732,113.7220,1000
...

I believe these files are effected:
/clickhouse/geoip_asn_blocks_ipv6_dictionary.xml
/clickhouse/geoip_asn_blocks_ipv4_dictionary.xml
/clickhouse/geoip_country_blocks_ipv6_dictionary.xml
/clickhouse/geoip_country_blocks_ipv4_dictionary.xml
/clickhouse/geoip_city_blocks_ipv4_dictionary.xml
/clickhouse/geoip_city_blocks_ipv6_dictionary.xml

Happy to submit a pull if you'd like.

**Comment by Slach** [comment]
@jagu2012 let's make PR
